### ISSUE TITLE
Code review for @ZMinghuiZ 

### ISSUE THREAD

**Issue by aditichadha1310** [AY2324S2-CS2113-T11-4/tp#64]
![image](https://github.com/AY2324S2-CS2113-T11-4/tp/assets/70324480/ec875291-88f4-40ee-b25c-87bea6a1b705)
Avoid complex statements.

Overall, good job!

**Comment by ZMinghuiZ** [comment]
> ![image](https://private-user-images.githubusercontent.com/70324480/316323196-ec875291-88f4-40ee-b25c-87bea6a1b705.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTI5MjEsIm5iZiI6MTcxMTU5MjYyMSwicGF0aCI6Ii83MDMyNDQ4MC8zMTYzMjMxOTYtZWM4NzUyOTEtODhmNC00MGVlLWIyNWMtODdiZWE2YTFiNzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAyMjM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYmMxYTNkZjE2MzQzODBjMzM1ZDUxMGMyMzEzMWEyZmJhNzRlYzhhZjIzNDMyNzUyMWM1M2M1YTBmY2VmODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yJ3MXgibk3NtVQv5RkmzBymMvKOoCTNsTcT4HBWcg5Y) Avoid complex statements.
> 
> Overall, good job!

Thanks for the feedback, have changed the complex statement into simpler one👍
